name: go_build

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release kube-resource-explorer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
    - uses: actions/checkout@v3

    - uses: notiz-dev/github-action-json-property@release
      id: kre-version
      with:
        path: 'release.json'
        prop_path: 'version'

    - uses: notiz-dev/github-action-json-property@release
      id: go-version
      with:
        path: 'release.json'
        prop_path: 'go_version'

    - uses: wangyoucao577/go-release-action@v1.31
      name: create binary
      with:
        github_token: ${{ secrets.PAT }}
        overwrite: true
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/kube-resource-explorer"
        binary_name: "kube-resource-explorer"
        extra_files: LICENSE README.md
